### ISSUE TITLE
NanoZoomer and brainreg

### ISSUE THREAD

**Issue by aeazraoui** [brainglobe/brainreg#114]
Hi,

Thank you for the great work ! I'd like to use brainglobe to reconstruct neuropixel probe tracks. I was wondering if brainreg can be used with whole slide scans containing several brain slices such as those we get on Nanozoomer ?

Thank you in advance.

All the best,
Anass

**Comment by adamltyson** [comment]
Hi @aeazraoui,

Currently it's only possible to register 3D images with BrainGlobe tools. For 2D data I would recommend [ABBA](https://biop.github.io/ijp-imagetoatlas/).

Thanks,
Adam
