### ISSUE TITLE
Remove niftyreg binaries from package

### ISSUE THREAD

**Issue by dstansby** [brainglobe/brainreg#116]
In the future we should remove the niftyreg binaries from the packages, and give users clear instructures on how to install niftyreg from `conda-forge`.

**Comment by adamltyson** [comment]
Or even better, just move to `conda install -c conda-forge brainreg` as the default installation option.

**Comment by lacan** [comment]
Perhaps linked to this, but on a windows installation using Mamba, the `niftyreg` binaries are installed in 
`CONDA_PREFIX\Library\bin`

Whereas in your `conda_install_path` method in `niftyreg_binaries.py` references them as being in 
`CONDA_PREFIX\bin`
https://github.com/brainglobe/brainreg/blob/fd6475f90e2cd1f45d961df4f897aaab2905be43/src/brainreg/backend/niftyreg/niftyreg_binaries.py#L17

Moreover, your test `if (bin_path / "reg_aladin").exists()` returns `False` for me, as the only way to get it to return `True` is to add `.exe`
```
if (bin_path / "reg_aladin.exe").exists():
```

So I guess you'd need to separate between Windows and Mac/Linux?  

Perhaps this is not the way, but it's the only way I managed to get Brainreg to work

**Comment by adamltyson** [comment]
@willGraham01 is this something you could take a look at?

**Comment by willGraham01** [comment]
Will take a look this afternoon & next week

**Comment by willGraham01** [comment]
Hi @lacan - taking a look at this, this morning. Just a couple of questions if that's OK:

> Moreover, your test if (bin_path / "reg_aladin").exists() returns False for me, as the only way to get it to return True is to add .exe
> ```if (bin_path / "reg_aladin.exe").exists():```

Did you need to edit the `bin_path` variable (defined [on the line above](https://github.com/brainglobe/brainreg/blob/3dec0a43719906201fabc218f6aa878ebe736d3f/src/brainreg/backend/niftyreg/niftyreg_binaries.py#L25-L27) the one you reference) to `CONDA_PREFIX\Library` _in addition_ to adding `.exe`, or did just adding `.exe` to `reg_aladin` work?

Can I also ask whether you had to add ".exe" to the program names in `parameter.py` to get the registration to work ([the lines are here](https://github.com/brainglobe/brainreg/blob/3dec0a43719906201fabc218f6aa878ebe736d3f/src/brainreg/backend/niftyreg/parameters.py#L153-L158))?
