### ISSUE TITLE
Document output files

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#13]
All brainreg output files are not completely clear what they are, this should be documented.

**Comment by Marilynb24** [comment]
Hello Adam, 
I'm using this conversation to ask some questions concerning the output file (if there is better place to ask, let me know I will repost). I used brainreg on an autofluo image and I'm looking a way to extract the transformation matrix and to apply it on the fluorescent channel of that image. Is there some possibilities to found such file? I saw different deformation field files in output. Can I use them to extract the transformation matrix and if so, which one should be used ?  Thanks in advance for your answer.

**Comment by adamltyson** [comment]
Hi,

If you use the `--debug` flag with brainreg, you can save the affine transform (in the `niftyreg` directory), but this is only for the initial, linear transformation step. The full registration is non-linear and so cannot be represented as a transformation matrix. The information is contained in either the deformation files that you've seen, or the control point files, also saved into `niftyreg` when you use the `--debug` flag.

However, if you use the `-d` flag, you can downsample and register as many additional channels as you like. As an example, taking the [tutorial example](https://docs.brainglobe.info/brainreg/tutorial), you could register two channels (lets use the `test_brain` file twice, as this dataset is only one channel):
```
brainreg test_brain brainreg_output  -d test_brain -v 50 40 40  --orientation psl --atlas allen_mouse_50um
```

Hope this makes sense

**Comment by Marilynb24** [comment]
Thanks for your clear answer Adam.
In fact I already tried the -d flag, but according to our results it seems the registration is fine on AF channel but not on other channels. I mean, the area detection fits well with AF but for others it looks like it is just a "superposition " of area detected from AF images to channel downsampled images. Images are downsampled but area detection doesn't match well for some structures, like a shift in z maybe, channel image structures seem appear before AF image structures and so, the area registration is late.
Hope it is clear.

**Comment by adamltyson** [comment]
Are your different channels aligned with each other?

The `-d` flag just applies the same registration to your additional channels. If they aren't aligned with each other, this won't work, but neither would using the registration output files directly.

**Comment by adamltyson** [comment]
Added to https://docs.brainglobe.info/brainreg/user-guide/output-files
