### ISSUE TITLE
group plugins for brainreg-register and segment

### ISSUE THREAD

**Issue by stephenlenzi** [brainglobe/brainreg#153]
see brainglobe/brainreg-napari#5 for discussion on this issue

**Comment by adamltyson** [comment]
This won't be done now. `brainreg-segment` has become [`brainglobe-segmentation`](https://github.com/brainglobe/brainglobe-segmentation) and will exist independently (and eventually support [`brainglobe-registration`](https://github.com/brainglobe/brainglobe-registration)).
