### ISSUE TITLE
[BUG] Installation via napari installer fails

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainreg#165]
**Describe the bug**
Installing via the napari installer gives the error described in https://forum.image.sc/t/error-with-brainreg-installation/89547

**To Reproduce**
Install the brainreg napari plugin through the GUI installer in a clean conda env with napari (presumably, haven't reproduced yet)

**Expected behaviour**
The plugin installs

**Computer used (please complete the following information):**
Conda with Python 3.10 on MacOS on a Silicon Mac

**Comment by adamltyson** [comment]
As I posted on the forum, this _may_ be related to [this issue](https://github.com/brainglobe/brainglobe-segmentation/issues/113) that was fixed in napari [here](https://github.com/napari/napari/pull/6013).

**Comment by adamltyson** [comment]
I think this is fixed now
