### ISSUE TITLE
[BUG] cannot install the lastest version from napari GUI

### ISSUE THREAD

**Issue by jingjie-li** [brainglobe/brainreg#171]
**Describe the bug**
Following the instructions from [here](https://brainglobe.info/tutorials/tutorial-whole-brain-registration.html), in the plugin installation page of napari, we can only get `brainreg-napari` for version `0.1.3`, which is not compatible with the latest napari_io.

`pip install brainreg[napari]` will give the latest correct version

**To Reproduce**
napari environment:
```
napari: 0.4.18
Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.2
SciPy: 1.11.4
Dask: 2023.12.1
VisPy: 0.12.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.3
```
**Screenshots**
![image](https://github.com/brainglobe/brainreg/assets/16413662/1b4cea8a-c494-48f8-be09-49a879d3e25e)

**Computer used (please complete the following information):**
ubuntu 20.04

**Comment by adamltyson** [comment]
Thanks @jingjie-li. We assumed this was due to a lack of the `napari` pypi trove classifier, but this was added, and then the new version released yesterday. The plugin shows up on the [napari hub](https://www.napari-hub.org/plugins/brainreg), but not in napari. Maybe there's a delay? I'll ask the napari devs.

We should also remove `brainreg-napari` from napari as this is confusing.

**Comment by adamltyson** [comment]
The napari hub listing is also missing some information. I wonder if `napari.yml` should be higher up in the repo, i.e. at `brainreg/napari.yml` not `brainreg/napari/napari.yml`?

**Comment by adamltyson** [comment]
Turns out this is a bug in the napari plguin engine, and @Czaki [has a fix](https://github.com/napari/npe2/pull/336).

**Comment by adamltyson** [comment]
Although we should be able to fix this in the interim by moving the napari.yaml file one level higher.

**Comment by adamltyson** [comment]
@brainglobe/active-devs shall we just wait a few days until this is fixed on the napari side? This would also fix cellfinder.

**Comment by willGraham01** [comment]
I'd say we wait if there's a fix coming in 2-3 days; saves us opening PRs on several of our repos (only to change them back again).

The `pip install` option is working for all of the packages currently, and we can always help people with installing via `pip` for a couple of days :)

**Comment by adamltyson** [comment]
This is now fixed, all the plugins appear in the napari plugin dialog (and I think it shouldn't need an update).
