### ISSUE TITLE
[FEATURE] Refactor `LoadFileException` into `brainglobe-utils`

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/brainreg#180]
The `LoadFileException` class is already defined as a stub in `brainglobe-utils.image_io` (versions 0.4.0 or above), and in `brainreg.core.exceptions` here as a fuller class.

We should refactor this expanded class into `brainglobe-utils`, and import it in `brainreg`.

**Comment by K-Meech** [comment]
I can look into this issue. Just to double check - the aim would be to replace [`ImageIOLoadException`](https://github.com/brainglobe/brainglobe-utils/blob/main/brainglobe_utils/image_io/utils.py#L5) from brainglobe-utils with [`LoadFileException`](https://github.com/brainglobe/brainreg/blob/main/brainreg/core/exceptions.py#L32) from `brainreg`?

**Comment by willGraham01** [comment]
Yeah - if you look at [`brainreg.core.main`](https://github.com/brainglobe/brainreg/blob/31e2111b073985dfa37c34035a443a717a724388/brainreg/core/main.py#L57) you'll see that `LoadFileException` is thrown after obtaining an error from `brainglobe-utils.image_io.load.load_any`.

The error thrown by `load_any` is of type `ImageIOLoadException`, which doesn't really do anything in terms of offering extra information. It would be better to move what's currently in `LoadFileException` into `ImageIOLoadException`, so that the [`load_img_stack`](https://github.com/brainglobe/brainglobe-utils/blob/5875b1b0ba5b2f99d4638e451c8f0486352de00f/brainglobe_utils/image_io/load.py#L157) function could then raise this error directly, saving us the `try/catch` block that we currently have in [`brainreg.core.main`](https://github.com/brainglobe/brainreg/blob/31e2111b073985dfa37c34035a443a717a724388/brainreg/core/main.py#L57).

`LoadFileExcaption` also currently takes a `error_type` argument to `__init__`, so we can potentially add cases to this in `brainglobe-utils` to cover other occasions where we throw an error on loading. EG [Here](https://github.com/brainglobe/brainglobe-utils/blob/5875b1b0ba5b2f99d4638e451c8f0486352de00f/brainglobe_utils/image_io/utils.py#L33) we could raise a `LoadFileException(error_type="memory")` for example.

**Comment by K-Meech** [comment]
Closing this issue, as all refactoring is now done + released.
