### ISSUE TITLE
[BUG] Doublecheck additional channels don't overwrite each other

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainreg#183]
**Describe the bug**
[We have a _suspicion_ that if folders of additional channels contain files with the same name, the output file gets overwritten.](https://forum.image.sc/t/use-registered-atlases-from-brainreg-for-segmentation-in-imaris/86206/49?u=alessandrofelder)

**To Reproduce**
Please enter full details of how to reproduce this bug.

**Expected behaviour**

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Computer used (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS] For macOS, please specify if you have an Intel or M1 CPU (M1 is likely if your mac is new).
- Version [e.g. 18.04]
- Hardware specs [e.g. 128 GB RAM, Xeon 4114 CPU].

**Additional context**

**Comment by alessandrofelder** [comment]
[Suspicion confirmed](https://forum.image.sc/t/use-registered-atlases-from-brainreg-for-segmentation-in-imaris/86206/54)

**Comment by lizard1111** [comment]
Ah, that was me over on image.sc. 
(https://github.com/brainglobe/brainreg/files/14471229/problem.solution.pdf)
A little more context, in case it helps.. 
My solution gives me a bit of anxiety, but it does the trick!
