### ISSUE TITLE
Registration fails in napari plugin if data is loaded with dask. 

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#202]
When loading data using dask (which is default when loading e.g. a directory of tiffs), brainreg fails with:

```
NotImplementedError: The out parameter is not fully supported. Received type ndarray, expected Dask Array
```

This used to work, so not sure if something has changed on the dask side

**Comment by adamltyson** [comment]
Using an old version of dask (2023.1.0) doesn't fix this, so I assume this is on our side.

**Comment by alessandrofelder** [comment]
Do you have an MRE for this @adamltyson ?

**Comment by adamltyson** [comment]
No, unfortnately. I noticed it while debugging something else.

**Comment by adamltyson** [comment]
This has been resolved by updating scikit-image (possibly this PR: https://github.com/scikit-image/scikit-image/pull/7009). 

Anyway, closing as this no longer seems to be an issue :). Will reopen if it turns out to be something else.
