### ISSUE TITLE
[BUG] conda-forge installation doesn't come with brainglobe_atlasapi

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/brainreg#206]
**Describe the bug**
Running `brainreg` CLI on sample-data in fresh conda environment with `brainreg` from `conda-forge` fails with `brainglobe_atlasapi` not found (at least on M2)

**To Reproduce**
Run this script (adapt local paths to `conda`/`mamba` and to sample data)
```bash
 #!/usr/bin/env bash -l
mamba env remove -n brainreg-conda-forge
mamba create -n brainreg-conda-forge python=3.10 -y
mamba activate brainreg-conda-forge
mamba install -c conda-forge brainreg -y
which python
which pip
which brainreg
brainreg ~/Downloads/brainreg-test-data/input/brain/ ~/Downloads/brainreg-metapackage-output/ -v 5 2 2 --orientation sal --atlas allen_mouse_25um
```
and observe this output:
```
/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/bin/python
/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/bin/pip
/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/bin/brainreg
Traceback (most recent call last):
  File "/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/bin/brainreg", line 6, in <module>
    from brainreg.core.cli import main
  File "/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/lib/python3.10/site-packages/brainreg/core/cli.py", line 14, in <module>
    from brainreg.core.main import main as register
  File "/Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge/lib/python3.10/site-packages/brainreg/core/main.py", line 4, in <module>
    from brainglobe_atlasapi import BrainGlobeAtlas
```

**Expected behaviour**
`brainreg` CLI terminates successfully and gives at least an approximately reasonable registration output.

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

\

**Computer used (please complete the following information):**

- OS: macOS
- Version: Sonoma 14.5
- Hardware specs: M2

**Additional context**

\

**Comment by willGraham01** [comment]
Just so we're not going completely insane, what's the output of running `pip list` after `mamba install -c conda-forge brainreg -y`? Presumably `brainglobe-atlasapi` is missing from the list.

`mamba list` should also hopefully give the same indication that it's missing.

**Comment by alessandrofelder** [comment]
Yes, output of `mamba list | grep brain` is:
```
# packages in environment at /Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge:
brainglobe-napari-io      0.3.3              pyhd8ed1ab_0    conda-forge
brainglobe-segmentation   1.2.2              pyh9208f05_0    conda-forge
brainglobe-space          1.0.2              pyhd8ed1ab_0    conda-forge
brainglobe-utils          0.4.0              pyhd8ed1ab_0    conda-forge
brainreg                  1.0.7              pyhd8ed1ab_0    conda-forge
```

**Comment by alessandrofelder** [comment]
If I add `pip install brainglobe-atlasapi` to the bash script, right after the installation of `brainreg` from conda-forge, I get an error with `pip's dependency resolver` which references `brainreg==0.0.0` ⁉️ 

```Installing collected packages: SimpleITK, xmltodict, pyparsing, loguru, fonttools, cycler, contourpy, PyMCubes, matplotlib, vtk, vedo, brainglobe-atlasapi
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
brainreg 0.0.0 requires brainglobe-utils>=0.4.2, but you have brainglobe-utils 0.4.0 which is incompatible.
Successfully installed PyMCubes-0.1.4 SimpleITK-2.3.1 brainglobe-atlasapi-2.0.6 contourpy-1.2.1 cycler-0.12.1 fonttools-4.53.0 loguru-0.7.2 matplotlib-3.9.0 pyparsing-3.1.2 vedo-2024.5.1 vtk-9.3.0 xmltodict-0.13.0
# packages in environment at /Users/alessandrofelder/mambaforge/envs/brainreg-conda-forge:
brainglobe-atlasapi       2.0.6                    pypi_0    pypi
brainglobe-napari-io      0.3.3              pyhd8ed1ab_0    conda-forge
brainglobe-segmentation   1.2.2              pyh9208f05_0    conda-forge
brainglobe-space          1.0.2              pyhd8ed1ab_0    conda-forge
brainglobe-utils          0.4.0              pyhd8ed1ab_0    conda-forge
brainreg                  1.0.7              pyhd8ed1ab_0    conda-forge```

**Comment by willGraham01** [comment]
> I get an error with pip's dependency resolver which references brainreg==0.0.0 ⁉️

Urgh I feel like I hit this weird behaviour right back when I started the tool reorganisation - `pip` and `conda` get their package information from different places. Could be the cause of the bug because I'm fairly sure `brainreg 0.0.0` doesn't list `atlasapi` as a dependency

**Comment by alessandrofelder** [comment]
Thanks @willGraham01 

>What's the output of pip list | grep brainglobe in the envrionment? Guessing it should say brainreg is at v0.0.0.

You guess correctly:

```
brainglobe-atlasapi           2.0.6
brainglobe-napari-io          0.3.3
brainglobe-segmentation       1.2.2
brainglobe_space              1.0.2
brainglobe-utils              0.4.0
brainreg                      0.0.0
```


Installing `brainglobe-atlasapi` from conda-forge in the script gives another error:
```
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                 

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==14.5=0
  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__unix==0=0
  - brainglobe-atlasapi -> click -> __unix
  - brainglobe-atlasapi -> click -> __win
  - brainglobe-atlasapi -> numpy -> __osx[version='>=10.9|>=11.0']
  - python=3.10 -> libsqlite[version='>=3.45.2,<4.0a0'] -> __osx[version='>=10.9|>=11.0']

Your installed version is: 14.5
```

**Comment by alessandrofelder** [comment]
> So adding niftyreg to the runtime dependencies should fix that... assuming conda installs them to a sensible place

Let's try

**Comment by willGraham01** [comment]
> The following specifications were found to be incompatible with your system:

This doesn't fill me with joy though. The issue I think is going to be the `click` dependency - https://github.com/conda-forge/click-feedstock/issues/45

**Comment by alessandrofelder** [comment]
Local testing suggests this is not quite fixed yet. While [things on conda-forge](https://anaconda.org/conda-forge/brainreg/files) look good (there is a new build which will include niftyreg there: brainreg 1.0.9, build 1), an older version of brainreg (1.0.7) is installed for me on Macbook M2. Explicitly calling
```bash
mamba install brainreg=1.0.9
```
fails with
```
Looking for: ['brainreg=1.0.9']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
The following package could not be installed
└─ brainreg 1.0.9**  is not installable because it requires
   └─ brainglobe-atlasapi, which requires
      └─ pymcubes, which does not exist (perhaps a missing channel)
```

**Comment by alessandrofelder** [comment]
It looks like `pymcubes` does not have [an ARM package on conda-forge](https://anaconda.org/conda-forge/pymcubes/files).
Additionally, I don't think we need `pymcubes` as a dependency of `brainglobe-atlasapi` - it's only needed for atlas packaging.

**Comment by willGraham01** [comment]
https://github.com/conda-forge/brainglobe-atlasapi-feedstock/pull/6 is now merged, which in particular removes the `pymcubes` dependency. So :crossed_fingers: the conda-forge install of `brainreg` should now be possible on ARM?

**Comment by alessandrofelder** [comment]
Yes, I hope so too. I am testing locally now.

**Comment by alessandrofelder** [comment]
I can locally install `brainreg` on M2 and [run it on our tutorial sample data](https://brainglobe.info/tutorials/tutorial-whole-brain-registration.html) through both CLI and `napari` plugin.
