### ISSUE TITLE
vtkplotter removed from PyPI

### ISSUE THREAD

**Issue by mkunst23** [brainglobe/brainreg#26]
Hi,

looks like vtkplotter has been removed from PyPI causing this error during brainreg installation.

ERROR: Could not find a version that satisfies the requirement vtkplotter (from imlib).

Thanks,
Michael

**Comment by adamltyson** [comment]
Hi Michael,

The vtkplotter dependency in imlib has been removed, and brainreg installation should now work as normal. Let me know if you have any problems.

Thanks,
Adam

**Comment by mkunst23** [comment]
Hi Adam,

yes that worked.

Thanks,
Michael
