### ISSUE TITLE
vtkplotter is required for brainreg installation but has been removed from PyPI.

### ISSUE THREAD

**Issue by pmascalchi** [brainglobe/brainreg#29]
Comment from forum on Dec 23 2020:
"Brainreg doesn’t use vtkplotter, so it seems like that may be left behind by something else (maybe an old version of brainrender?). "

**Comment by adamltyson** [comment]
This should be fixed (https://github.com/brainglobe/brainreg/issues/26). Could you try updating `imlib`?

**Comment by pmascalchi** [comment]
Hmm, installing imlib fails on its own, saying vtkplotter is missing.
Do I need to point to a specific version of imlib?

**Comment by adamltyson** [comment]
Can you try specifying `0.1.0`?

**Comment by pmascalchi** [comment]
Says "no matching distrib"

**Comment by adamltyson** [comment]
Great. Numpy has stopped supporting Python <3.7, so I have too.

Is brainreg working now?

**Comment by pmascalchi** [comment]
Installation of brainreg goes through now, thanks!
