### ISSUE TITLE
Add options to try different types of image preprocessing

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#3]
Currently the preprocessing is hard coded. There should be options for different types of filters etc to allow systematic optimisation

**Comment by chrisroat** [comment]
I would actually propose you do the opposite -- do not use this package to do any preprocessing, besides what is necessary internally for the algorithm's accuracy.

As a new user, I wanted to explore several different sets of parameters to see what their effects were (I ran 3000 registrations on our cluster).  I found a lot of time was spent on the initial IO/downsampling -- I had saved our data in single TIFFs which hits a single-threaded downsampling "slow path".  (I also was surprised to see that the xy-downsampling and z-downsampling use different libraries.)

In the end, I found it better to initially downsample our data to 10um/25um/50um (the provided atlas resolutions), and then register to each without downsampling.  It was a minor increase in disk space, which then allowed the registration to be relatively quick.

If you open yourself to allowing a combinatorial explosion of data formats X downsampling algorithms X preprocessing, you may find yourself optimizing/debugging/implementing/releasing code paths unrelated to your core mission of registration.

IMHO, you could
- support only a few data formats (possibly include a self-describing format like xarray, so the resolution/orientation flags are not needed)
- remove any downsampling support

I think it's acceptable to just focus on the core registration in this package, and jettison the rest.  You could provide separate code examples or a separate utility to give people an example of how to downsample to a supported format.

**Comment by adamltyson** [comment]
Thanks for your input @chrisroat, much appreciated!

However, I disagree, mostly because I view the main aim of this package to be _accessible_ whole-brain registration (more work required though!). There are certainly more accurate packages, but many of them require considerable computational skills to install and run. Many users can't (or don't want to) carry out preprocessing in other packages and want streamlined software that just takes raw data as input.

This being said, you raise very good points, and I think there's a compromise somewhere that:
* Allows some flexibility for the novice user
* Allows advanced users to leverage brainreg as part of a more complex workflow (e.g. just as a Python wrapper around other registration libraries). 
* Doesn't provide a huge maintenance burden.

**Comment by adamltyson** [comment]
I think we're on the same page, what I'm planning is something like:
* The [brainreg napari plugin](https://github.com/brainglobe/brainreg-napari) gradually becomes the entry point for novice users. I/O can then be handled by other plugins, and the user can leverage existing packages, such as scikit-image for preprocessing (@jni - are there plans to create a general napari-skimage plugin?).
* This package has more of a focus on advanced users, maybe also creating a proper Python API. I'd be interested in how the package could be improved for you if usability for novices was less important?

**Comment by chrisroat** [comment]
Cool!  We do agree.  :)

Yes, offloading pieces to napari and skimage/ndimage sounds like a good approach.

Here are a few ideas -- feel free to take or leave:

- I think a good python API would be cool.  You could likely model off of skimage or ndimage.
- Try allowing self-describing format like [xarray](https://xarray.pydata.org/en/stable/), and define a (maybe *the*) standard for 3d imaging planes -- how to name axes and define positive directions.  I got myself confused a couple times with the orientation stuff.  xarray is powerful, but here it would be simple numpy wrapper w/axes labels and coordinates.  Then one doesn't need the voxel size or orientation flags.
- More documentation around the flags and what they do -- maybe a simple example for each flag showing how it helps in some situation (binding energy, number of control points, histogram bins)
- Is it correct that n-steps and use-n-steps would be redundant if the downsampling happens elsewhere?  Meaning, if I have downsampled to my desired resolution, would I set these to be the same?
- For debugging, outputting every step of the affine/freeform stages would be illuminating.  (And even allowing zero steps, so I could check I got the orientation correct...)
- Some FAQs about various warning messages ,e.g:
```
Atlas value: 312782566 not found in registered atlas. Setting registered volume to 0.
```

**Comment by jni** [comment]
> are there plans to create a general napari-skimage plugin?

Yes! But they are tied up with skimage2 plans (which includes defining a bunch of standard APIs, e.g. a generic API for all registration functions), so I estimate an "official" plugin will take 6mo-1y to come out.
