### ISSUE TITLE
Register individual 2D sections to Atlas

### ISSUE THREAD

**Issue by MathieuBo** [brainglobe/brainreg#32]
Hi there!

Would it be possible to register individual mouse brain sections to the Atlas? 
I have seen that @adamltyson was developing [slicereg](https://github.com/adamltyson/slicereg) however as it seems to be based on amap so I am not sure it is still under development or whether it will be included in brainreg. 

Putatively, if 4-5 sections of the same brain need to be registered, would it be better to register each of them independently or to register altogether? 

Thanks!

**Comment by adamltyson** [comment]
Hi,

slicereg is now developed by @nickdelgrosso, over at [BrainGlobe/slicereg](https://github.com/brainglobe/slicereg). It's not ready for general use yet though (I think).

> Putatively, if 4-5 sections of the same brain need to be registered, would it be better to register each of them independently or to register altogether?

It kind of depends on the tool you're using, and the data. If they're right next to each other, you can probably register them together, if not separately.

Cheers,
Adam
