### ISSUE TITLE
error of registration

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/brainreg#36]
the data has been registrated successfully. but recently, when the data is registrated, there is error like this.

2021-06-01 16:16:50 PM - INFO - MainProcess run.py:56 - Registering
2021-06-01 16:16:50 PM - INFO - MainProcess run.py:76 - Starting affine registration
Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 281, in safe_execute_command
    subprocess.check_call(
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii -ref G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii -aff G:\ms20output_TIFF\output1\registration\niftyreg\affine_matrix.txt -res G:\ms20output_TIFF\output1\registration\niftyreg\affine_registered_atlas_brain.nii -omp 46' returned non-zero exit status 3221225477.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\registration.py", line 73, in register_affine
    safe_execute_command(
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\imlib\general\system.py", line 293, in safe_execute_command
    raise SafeExecuteCommandError(
imlib.general.system.SafeExecuteCommandError:
-------------------------
Process failed:
 -------------------------
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin] Command line:
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
         c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii -ref G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii -aff G:\ms20output_TIFF\output1\registration\niftyreg\affine_matrix.txt -res G:\ms20output_TIFF\output1\registration\niftyreg\affine_registered_atlas_brain.nii -omp 46
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin] OpenMP is used with 46 thread(s)
[reg_aladin_sym] Parameters
[reg_aladin_sym] Platform: cpu_platform
[reg_aladin_sym] Reference image name: G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii
[reg_aladin_sym]        1742x1120x1489 voxels
[reg_aladin_sym]        0.01x0.01x0.01 mm
[reg_aladin_sym] Floating image name: G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii
[reg_aladin_sym]        1320x800x1140 voxels
[reg_aladin_sym]        0.01x0.01x0.01 mm
[reg_aladin_sym] Maximum iteration number: 5
[reg_aladin_sym]        (10 during the first level)
[reg_aladin_sym] Percentage of blocks: 50 %
[reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

-------------------------
please read the logs at G:\ms20output_TIFF\output1\registration\niftyreg\affine.log and G:\ms20output_TIFF\output1\registration\niftyreg\affine.err
-------------------------
command: c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii -ref G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii -aff G:\ms20output_TIFF\output1\registration\niftyreg\affine_matrix.txt -res G:\ms20output_TIFF\output1\registration\niftyreg\affine_registered_atlas_brain.nii -omp 46
-------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\CIBR-ImFacility-WS1\anaconda3\envs\cellfinder\Scripts\cellfinder.exe\__main__.py", line 7, in <module>
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\cellfinder\main.py", line 53, in main
    register(
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\main.py", line 65, in main
    run_niftyreg(
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\run.py", line 77, in run_niftyreg
    brain_reg.register_affine()
  File "c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\backend\niftyreg\registration.py", line 79, in register_affine
    raise RegistrationError(
brainreg.backend.niftyreg.registration.RegistrationError: Affine registration failed;
-------------------------
Process failed:
 -------------------------
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin] Command line:
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
         c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii -ref G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii -aff G:\ms20output_TIFF\output1\registration\niftyreg\affine_matrix.txt -res G:\ms20output_TIFF\output1\registration\niftyreg\affine_registered_atlas_brain.nii -omp 46
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin]
[c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin] OpenMP is used with 46 thread(s)
[reg_aladin_sym] Parameters
[reg_aladin_sym] Platform: cpu_platform
[reg_aladin_sym] Reference image name: G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii
[reg_aladin_sym]        1742x1120x1489 voxels
[reg_aladin_sym]        0.01x0.01x0.01 mm
[reg_aladin_sym] Floating image name: G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii
[reg_aladin_sym]        1320x800x1140 voxels
[reg_aladin_sym]        0.01x0.01x0.01 mm
[reg_aladin_sym] Maximum iteration number: 5
[reg_aladin_sym]        (10 during the first level)
[reg_aladin_sym] Percentage of blocks: 50 %
[reg_aladin_sym] * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

-------------------------
please read the logs at G:\ms20output_TIFF\output1\registration\niftyreg\affine.log and G:\ms20output_TIFF\output1\registration\niftyreg\affine.err
-------------------------
command: c:\users\cibr-imfacility-ws1\anaconda3\envs\cellfinder\lib\site-packages\brainreg\bin\nifty_reg\win64\reg_aladin -ln 6 -lp 5 -flo G:\ms20output_TIFF\output1\registration\niftyreg\brain_filtered.nii -ref G:\ms20output_TIFF\output1\registration\niftyreg\downsampled_filtered.nii -aff G:\ms20output_TIFF\output1\registration\niftyreg\affine_matrix.txt -res G:\ms20output_TIFF\output1\registration\niftyreg\affine_registered_atlas_brain.nii -omp 46
-------------------------

**Comment by adamltyson** [comment]
I'll tackle this over at [image.sc](https://forum.image.sc/t/brain-registration/53412), and close this issue.

Would you mind only raising issues in one place (i.e. image.sc or GitHub)? I get notified of them all, and I try to reply ASAP, but sometimes it may take a few days/weeks to get round to everything. Thanks!
