### ISSUE TITLE
napari plugin fails to install correctly (linux, python 3.9)

### ISSUE THREAD

**Issue by stephenlenzi** [brainglobe/brainreg#38]
fresh install on Linux 4.15.0-140-generic x86_64

conda env python 3.9

pip install brainreg .[dev]

then simply running napari in the terminal leads to the following error:

WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
14:50:20 WARNING Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

14:50:20 WARNING This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

I have also tried to install napari into the same env (pip install napari[all]) but get the same error.

**Comment by adamltyson** [comment]
I think this is a known issue: https://github.com/napari/napari/issues/1457.

`conda install -c conda-forge napari` should work.

**Comment by stephenlenzi** [comment]
thanks - this resolves the issue
