### ISSUE TITLE
Add additional registration backends

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#41]
E.g. elastix

**Comment by adamltyson** [comment]
Started on elastix backend here: 68e4c97cd2d16bd7ec3d5b31dc9b9f299ca5dd5e

**Comment by ablot** [comment]
Is there any reason to prefer `itk` or `SimpleITK`? Brainregister seems to use the latter and you have `itk`.

Related, I  tried to install `pip install itk-elastix` on two machines (Mac and Linux) and on both I get the same error when trying to access an elastix method:

```
File ~/.conda/envs/cellfinder/lib/python3.9/site-packages/itk/support/../ElastixPython.py:13, in <module>                                                    │
     11 # Import the low-level C/C++ module                                                                                                                  │
     12 if __package__ or "." in __name__:                                                                                                                   │
---> 13     from . import _ElastixPython                                                                                                                     │
     14 else:                                                                                                                                                │
     15     import _ElastixPython                                                                                                                            │
                                                                                                                                                             │
AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid  
```

Did you have a similar issue? Do I need to install extra C library to get that working (SimpleITK works on the same machine).

**Comment by adamltyson** [comment]
>Is there any reason to prefer itk or SimpleITK? 

I can't remember the exact reason to be honest. I'd used `itk-elastix` with some other projects, and it worked well.

It's been a long time since I've looked at the `elastix` branch, so I would recommend opening an issue at the `itk-elastix` repo if you're having issues with their package.

**Comment by adamltyson** [comment]
May scrap this in favour of creating workflows within napari that allow use of other registration tools with BG atlases.

**Comment by adamltyson** [comment]
Closing in fsvour of https://github.com/brainglobe/brainglobe-registration
