### ISSUE TITLE
Sub-brain region registration

### ISSUE THREAD

**Issue by JulesScholler** [brainglobe/brainreg#49]
Hi there, it's me again!

Any plan on allowing to register a single hemisphere or full brain without olfactory bulb for example?

If you did not implement anything yet, I might give it a try because it is often the case that we have partial brains and it becomes really cumbersome to register them if possible at all.

I already have a plan in mind, however I am open to any suggestions.

Cheers,
Jules

**Comment by adamltyson** [comment]
Hi @JulesScholler - lots of plans, but unfortunately no time to carry them out!

If you could give this a go, that would be great. I'm going to close this issue though, as this feature is being tracked in https://github.com/brainglobe/brainreg/issues/6

Cheers
Adam
