### ISSUE TITLE
save_original_resolution breaks additional_image_downsample

### ISSUE THREAD

**Issue by npeschke** [brainglobe/brainreg#50]
the `save_original_orientation` option is a great addition but it redefines `atlas` 

https://github.com/brainglobe/brainreg/blob/5164329f9f057273fed70336eba601bde9472190/brainreg/backend/niftyreg/run.py#L113-L116

and thus, looses the `atlas.resolution` field which is needed later in `additional_image_downsample`

https://github.com/brainglobe/brainreg/blob/5164329f9f057273fed70336eba601bde9472190/brainreg/backend/niftyreg/run.py#L189-L193

**Comment by adamltyson** [comment]
Thanks for this @npeschke, I released an RC with your fix (`pip install brainreg==0.3.1rc0`). Would you mind giving it a test before I make a full release?

**Comment by npeschke** [comment]
Just tested it and it ran fine with the following options
```bash
conda create -y -n test_brainreg -c conda-forge python=3.9 scipy && conda activate test_brainreg && pip install brainreg==0.3.1rc0
brainreg reg_file_paths.txt brainreg_test -d downsample_file_paths.txt -v 6 3.25 3.25 --debug --save-original-orientation --atlas allen_mouse_25um --orientation LPI
```

**Comment by adamltyson** [comment]
Great, thanks. I'll release `0.3.1` later today.

**Comment by npeschke** [comment]
Thanks for the quick response!
