### ISSUE TITLE
Modularized dependencies

### ISSUE THREAD

**Issue by chrisroat** [brainglobe/brainreg#52]
Installing brainreg brings in 3.4GB of dependencies, as measured by my virtualenv folder's size.  I see many things I don't think(?!) I need for a simple registration - e.g. ipython, jinja2, pyside2, sphinx, and napari.  [I could be wrong here, of course.]

Might I suggest verifying what is needed, and perhaps having separate extras for some of this functionality?  This could leave the core "pip install brainreg" to bring in a minimal set of dependencies to run registration.

**Comment by adamltyson** [comment]
Most of the dependencies are needed to view the data, which I think most novice users appreciate, but do add some bloat. I wish there was a way of setting up `pip install brainreg[minimal]` for advanced users, but I think we may need `pip install brainreg` and `pip install[gui]` as you suggest.

There may also be some work to look at the manifest and ensure no test data etc is packaged up into the distribution.

**Comment by adamltyson** [comment]
Closed as completed by @willGraham01
