### ISSUE TITLE
Tool to check for orientation

### ISSUE THREAD

**Issue by JulesScholler** [brainglobe/brainreg#59]
Not really an issue but more of a question.

Is there a practical way to check the orientation of the data in a user friendly manner? I usually use BG-space to apply a transformation and then display the data along the Atlas but it requires some coding. I found out that the most difficult part of the registration for users is actually finding the orientation because if you mess up then the registration result is bad and people will start tweaking the parameters without realizing that the data was not aligned correctly.

Thanks and keep up the amazing work :).

**Comment by adamltyson** [comment]
Hey @JulesScholler, does this need a tool, or just better documentation? TBH I thought the docs were better, but it's certainly not trivial to work out the orientation from what we have.

You shouldn't have to reorient your data before using brainreg.

**Comment by JulesScholler** [comment]
You can add more documentation but I think most people are not going to understand right away how to define the orientation with the 3 letters scheme. Just displaying the transformed input data and the atlas before registration as a validation step is much easier (I think) to grasp if the input orientation is correct or not.

Don't get me wrong, the doc is great, but I still sometime fuck up the determination of the orientation and if I had visualized the transformed data beforehand I could have spotted sooner the problem.

MIRACL pipeline has another approach where they show the user max projections and ask what plane it is (sagital, horizontal, etc) and then figures out by itself the input orientation. I guess this could be an option in brainreg, or even better an automatic way of determining the input orientation using a simple classifier and a few features computed on the max-projections (e.g. sphericity and area of the segmented shape).

**Comment by adamltyson** [comment]
I like these ideas, but I'm hesitant to add more code to solve a documentation problem (I've got limited time to support/maintain this in my spare time), but more "interactive" docs (e.g. if your data is X, then the first letter is Y etc etc) may help this problem. Displaying data is also a pain as many users use the CLI tool for very large datasets on very slow network drives.

**Comment by JulesScholler** [comment]
In my view I would add a parsed argument --orientation-help that can be 

- 'off' (default) and the behavior is like now
- 'gui' and you display for validation or use MIRACL approach
- 'automatic' and you use an automatic approach at your own risk

Doing that you add more flexibility without changing the behavior for current users and the default behavior is not adding any latency for network drives.

**Comment by adamltyson** [comment]
I'd love that, but TBH I just can't commit to anything other than bug fixes at this point.

**Comment by JulesScholler** [comment]
I will dedicate some time for this issue, i.e. having an automatic way of determining the input orientation and having an interactive way of fixing the output. Requirements are:

- Should work with single hemispheres
- Should work with not aligned data (to some extent)
- Should be quick to not add unwanted overhead

The workflow I see would be to add an orientation option 'interactive' or 'auto' which would try to automatically guess the input orientation. Then it would open a Napari window with reference and oriented input data and buttons to correct by rotating horizontally and vertically. When the data is oriented with the reference brain the user closes the Napari viewer and the rest of the pipeline is run.

How about that @adamltyson ? I will start working on automatically finding the input orientation.

**Comment by adamltyson** [comment]
Sounds great! My only thought is that if it starts up napari, maybe it's better placed in the brainreg-napari plugin, and the brainreg command line tool can continue to be a fully automated, headless version?

Users could use the napari plugin to begin with, then use the CLI once they're confident of the orientation, and have optimised registration parameters. 

Thanks for looking into this, the orientation is confusing a few people!

**Comment by JulesScholler** [comment]
Ok so the 'automatic' option will be available in the CLI and we can add it later on in the Napari plugin. I agree the interactive approach should be added only in the Napari plugin since it requires this dependency.

**Comment by adamltyson** [comment]
Sounds great. Thanks @JulesScholler!

**Comment by JulesScholler** [comment]
So I tried different 'physics' things but they all failed when testing on different angles (I added a random rotation of 0 up to 15° around one of the three axis).  Basically looking at the inertia tensor can tell you how to find the three axis but not the direction so you end up with 'a/p' 's/i' and 'l/r' without being sure which one it is.

I will focus on finding some symmetry measures to try and find the direction.

Last approach would we to train a random forest or equivalent classification tool using a few features on the maximum intensity projection but this will require extra work and might be a pain to package because the trained classifier should ship with brainreg.

**Comment by JulesScholler** [comment]
After playing quite a while with it I think that it is a bad idea to try and find automatically the orientation. Main argument is that the method will either be atlas specific or need machine learning and we don't want that in brainreg. I made a tool to interactively check that the orientation is good:

![image](https://user-images.githubusercontent.com/23705332/172410863-00214ca0-c5d5-4c21-ab89-209e32988e74.png)
Top is the reference atlas, averaged for all directions and bottom is the aligned input data with wrong input

![image](https://user-images.githubusercontent.com/23705332/172409917-160b3147-5d52-4eb8-9301-fcef3aca72b6.png)
Top is the reference atlas, averaged for all directions and bottom is the aligned input data with correct input


Advantages is that it works out of the box with all the atlases, drawback is you need to load the atlas twice (once for interactive alignment and one when the pipeline is run). Let me know if you like the solution and I'll send a PR.

**Comment by adamltyson** [comment]
> We are testing it internally but so far so good! 

Awesome. I think we've got one more brainreg PR to merge on our side, then we can get the orientation PR merged, then this one. I'm answering a lot of orientation questions, so this would make my life a lot easier!
