### ISSUE TITLE
Add test run with conda installation of `niftyreg`

### ISSUE THREAD

**Issue by dstansby** [brainglobe/brainreg#74]
Once https://github.com/brainglobe/brainreg/pull/68 is merged a GH actions job should be added that installs niftyreg from conda. This should show up as increased coverage, as it will hit the code paths introduced in https://github.com/brainglobe/brainreg/pull/68 to use the conda installation of `niftyreg`.

**Comment by adamltyson** [comment]
Closed with https://github.com/brainglobe/brainreg/pull/134
