### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#77]
Now NityReg is on conda, we should be able to more easily support macOS. This would require:

- [ ] Supporting system installations of NityReg (rather than the packaged binaries)
- [ ] Document conda installation of NiftyReg (and maybe brainreg)
- [ ] Add tests for macOS

**Comment by JoeZiminski** [comment]
Adding based on our discussion last week (will work on this Wednesday):

the "napari[pyside2]>=0.3.7", line in brainreg setup.py causes issues with installation, requiring a much earlier version of napari and other packages to be erroneously installed. Removing [pyside2] means it installs, but still need to determine how this effects napari.

One solution (which I think has been already suggested for different reasons) is, as I understand it, to use the setup.cfg to partition the requirements into [gui] and [no_gui] streams, as not installing the gui will avoid install issues on macos M1 and M2. 

Need to do a bit more digging to understand why this [pyside2] issue occurs maybe there is also another workaround to allow gui installs on M1 and M2

**Comment by adamltyson** [comment]
Closed as completed
