### ISSUE TITLE
[BUG] ERROR: Cannot install brainreg==0.0.2 .... 

### ISSUE THREAD

**Issue by Hanbing1999** [brainglobe/brainreg#78]
**Describe the bug**
After I create a new env " Brainreg" and conda activate it. Then I run `pip install brainreg`

It reported `ERROR: Cannot install brainreg==0.0.2, brainreg==0.0.3, brainreg==0.1.1, brainreg==0.1.3, brainreg==0.1.4, brainreg==0.1.6, brainreg==0.1.7, brainreg==0.1.8 and brainreg==0.1.9 because these package versions have conflicting dependencies`

**To Reproduce**

**Expected behaviour**

**Log file**

**Screenshots**
<img width="960" alt="image" src="https://user-images.githubusercontent.com/67142892/173694673-48e86541-b9ad-4f65-b834-7028f44c1967.png">

- OS:  macOS, M1 CPU
- Version: 12.0.1
- Hardware specs: 1 TB flash storage and external 2TB USB DISK

**Additional context**

Thanks for your time!

**Comment by Hanbing1999** [comment]
solved! Python version should be updated to 3.9

**Comment by adamltyson** [comment]
@Hanbing1999 Just FYI, we don't support brainreg on macOS yet, and it will be some work to get it up and running on M1.

**Comment by nataliekoh** [comment]
I had issues installing brainreg on Windows as well. It should be noted in the documentation that Python 3.9 is required for the installation to work; that solved my issue.
