### ISSUE TITLE
[BUG] "Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib" when using 'test_brain' to test brainreg 

### ISSUE THREAD

**Issue by Hanbing1999** [brainglobe/brainreg#79]
**Describe the bug**
When using the` test_brain` dataset to test the brainreg, it reported the following error: 
```
-------------------------
Process failed:
 dyld[12064]: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /Users/hanbing/opt/anaconda3/envs/brainreg/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin
  Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)
-------------------------

-------------------------
please read the logs at brainreg_output/niftyreg/affine.log and brainreg_output/niftyreg/affine.err
-------------------------
command: "/Users/hanbing/opt/anaconda3/envs/brainreg/lib/python3.9/site-packages/brainreg/bin/nifty_reg/osX/reg_aladin" -ln 6 -lp 5 -flo "brainreg_output/niftyreg/brain_filtered.nii" -ref "brainreg_output/niftyreg/downsampled_filtered.nii" -aff "brainreg_output/niftyreg/affine_matrix.txt" -res "brainreg_output/niftyreg/affine_registered_atlas_brain.nii" -omp 6
-------------------------

```

**Log file**

[brainreg_2022-06-14_16-48-49.log](https://github.com/brainglobe/brainreg/files/8904550/brainreg_2022-06-14_16-48-49.log)
[affine.log](https://github.com/brainglobe/brainreg/files/8904551/affine.log)

**Desktop (please complete the following information):**

OS: macOS, M1 CPU
Version: 12.0.1
Hardware specs: 1 TB flash storage and external 2TB USB DISK
Python version: 3.9

**Comment by adamltyson** [comment]
Hi @Hanbing1999 this is an existing issue, as brainreg doesn't support macOS. This is on the roadmap though. Please follow https://github.com/brainglobe/brainreg/issues/77 to track updates.

**Comment by Hanbing1999** [comment]
Thanks! I tried this pipeline in the Windows, and it works.
