### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/brainreg#8]
Using napari (as a plugin?). For choosing parameters, running reg and visualising results.

**Comment by vigji** [comment]
Also for check quickly if the specified orientation is correct!

**Comment by adamltyson** [comment]
With the new napari plugin hooks, this should be pretty straightforward. Still a pain we have to save to disk, but not much we can do about that. Although we wouldn't have to save the final tiffs if we didn't want to.

Could also provide a small brain as sample data with a napari hook.

**Comment by stephenlenzi** [comment]
https://github.com/brainglobe/brainreg-napari

**Comment by adamltyson** [comment]
GUI with basic functionality now in [brainreg-segment](https://github.com/brainglobe/brainreg-napari)
