### ISSUE TITLE
[BUG] pandas deprecation warning

### ISSUE THREAD

**Issue by dstansby** [brainglobe/brainreg#81]
**Describe the bug**
I'm currently testing `brainreg-napari`, and the tests emit the following warning that is coming from `brainreg`:

```python
  /Users/dstansby/projects/napari/brainreg/brainreg/utils/volume.py:93: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
    df = df.append(
```

**To Reproduce**
Please enter full details of how to reproduce this bug.

**Expected behaviour**

**Log file**
Please attach the log file if relevant (e.g. `output/cellfinder_2019-12-17_13-29-46.log`)

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. Linux, Windows, macOS] For macOS, please specify if you have an Intel or M1 CPU (M1 is likely if your mac is new).
- Version [e.g. 18.04]
- Hardware specs [e.g. 128 GB RAM, Xeon 4114 CPU].

**Additional context**

**Comment by adamltyson** [comment]
Thanks for raising @dstansby. This has been fixed by @JulesScholler now that https://github.com/brainglobe/brainreg/pull/62 has been merged.
