### ISSUE TITLE
[Feature] Make it easier to use an existing registration to transform a new channel

### ISSUE THREAD

**Issue by raacampbell** [brainglobe/brainreg#88]
When registering data with Elastix the transform parameters are saved to disk and it is possible to use the `transformix` command to rapidly apply these parameters to a new volume. It seems hard to do the same with nifty/brainreg.

Specific use case: I register to the atlas the downsampled autofluoresence channel. I later extract features from the full-res images and produce full-size binary masks that indicate the locations of these features. The binary images are downsampled and I want to be able to transform them into the atlas space. I might re-make these binary images more than once, so it would be convenient to have a fast way of transforming them based on existing parameters. Recalculating the transform each time would be annoying.

**Comment by raacampbell** [comment]
There is an additional issue here: I forgot that the ARA is registered into the sample space. So I think all I need to do with my binary mask image is flip it so it is in the same orientation as the registered atlas. Then everything will overlay. 

The issue I raise is therefore only a concern if the sample is registered into the atlas space. brainreg does not seem to do this, though. Can it?

**Comment by adamltyson** [comment]
>There is an additional issue here: I forgot that the ARA is registered into the sample space. So I think all I need to do with my binary mask image is flip it so it is in the same orientation as the registered atlas. Then everything will overlay.

That should work. If for any reason the flipping is annoying, you can use `--save-original-orientation` which will save the registered annotations with the same orientation as the input data.

> The issue I raise is therefore only a concern if the sample is registered into the atlas space. brainreg does not seem to do this, though. Can it?

brainreg does both by default. It will output both the atlas annotations transformed to sample space, and the sample transformed to atlas space.

**Comment by adamltyson** [comment]
Either way, I think this feature should be added.

**Comment by raacampbell** [comment]
Ok, I understand how everything is named now. I agree, then, that the feature would be helpful.

**Comment by LzEfreet** [comment]
> > There is an additional issue here: I forgot that the ARA is registered into the sample space. So I think all I need to do with my binary mask image is flip it so it is in the same orientation as the registered atlas. Then everything will overlay.
> 
> That should work. If for any reason the flipping is annoying, you can use `--save-original-orientation` which will save the registered annotations with the same orientation as the input data.
> 
> > The issue I raise is therefore only a concern if the sample is registered into the atlas space. brainreg does not seem to do this, though. Can it?
> 
> brainreg does both by default. It will output both the atlas annotations transformed to sample space, and the sample transformed to atlas space.

emmm, I wonder how to get wraped reference image after registration from atlas to sample, instead of  wraped annotation, what should I do for it? Thanks.

**Comment by adamltyson** [comment]
@LzEfreet to clarify, you want to get the reference atlas image, but warped to the coordinate space of your sample image? This is possible, but you'd have to use [NiftyReg](https://github.com/KCL-BMEIS/niftyreg) directly and it wouldn't be trivial. I can work out the command that you'd need if that's what you want to do.

**Comment by LzEfreet** [comment]
> @LzEfreet to clarify, you want to get the reference atlas image, but warped to the coordinate space of your sample image? This is possible, but you'd have to use [NiftyReg](https://github.com/KCL-BMEIS/niftyreg) directly and it wouldn't be trivial. I can work out the command that you'd need if that's what you want to do.

OK, I see. I just wonder how wraped atlas image would be after brainreg registration.

**Comment by adamltyson** [comment]
Closing. Will be addressed in https://github.com/brainglobe/brainglobe-registration
